@startuml Twamp
skinparam sequenceMessageAlign center

group Control-Connection
"Control-Client" --> Server: Start TCP Connection
Server -> "Control-Client": Greetings Message

"Control-Client" -> Server: { Mode, Integrity/Security? }
Server -> "Control-Client": Accept Mode + **start_time**
end

"Control-Client" -> Server: Create Test Session + TWAMP-Control Message
"Control-Client" <- Server: Ok + info

"Control-Client" -> Server: Start-Sessions
"Control-Client" <- Server: Ok

... After (or not) Session-Sender and Session-Reflector\nexchanges test packets ...

"Control-Client" -> Server: Stop All

@enduml
